
#This Make file is the first file to run for installing, updating and uninstalling any supported tool
update:
	./scripts/update.sh

netgen:
	./scripts/install_netgen.sh

magic:
	./scripts/install_magic.sh

xschem:
	./scripts/install_xschem.sh

sky130a_pdks:
	./scripts/install_sky130A.sh

clean_netgen:
	./scripts/rm_netgen.sh

clean_magic:
	./scripts/rm_magic.sh

clean_xschem:
	./scripts/rm_xschem.sh

update_netgen:
	./scripts/rm_netgen.sh
	./scripts/install_netgen.sh

update_magic:
	./scripts/rm_magic.sh
	./scripts/install_magic.sh

update_xschem:
	./scripts/rm_xschem.sh
	./scripts/install_xschem.sh

update_all_tools:
	./scripts/rm_netgen.sh
	./scripts/rm_magic.sh
	./scripts/rm_xschem.sh
	./scripts/install_netgen.sh
	./scripts/install_magic.sh
	./scripts/install_xschem.sh


    





